VIDEO_SOURCE = "test4.mp4"

VEHICLE_MODEL_PATH = "yolov8n.pt"
PLATE_MODEL_PATH = "license_plate_detector.pt"

VEHICLE_CLASSES = [2, 3, 5, 7]

CONF_VEHICLE = 0.25
CONF_PLATE = 0.30

PROCESS_WIDTH = 1920
PROCESS_HEIGHT = 1080

DISPLAY_WIDTH = 1280
DISPLAY_HEIGHT = 720

LINE_A_Y = 500
LINE_B_Y = 830

REAL_DISTANCE_METERS = 10
SPEED_LIMIT_KMH = 50

MIN_BOX_WIDTH = 50

OCR_EVERY_N_FRAMES = 15

MAX_SCREENSHOTS = 5
SCREENSHOT_FOLDER = "speeding_images"
EXCEL_FILE = "speed_log.xlsx"